name: kertaus
on: workflow_dispatch
permissions: 
  contents: write

env:
  MYNAME: Reima
  EVENT_NAME: ${{github.event_name}}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "$MYNAME"
          echo "Github event $GITHUB_EVENT_NAME
          echo "Context event ${{github.event_name}}"
          echo "My env event $EVENT_NAME
          echo "Event detail ${{github.event.action}}"
      - name: EhdollinenEka
        if: ${{github.event.action == 'sadfa'}}
        run: echo "Avattiin uusi issue" 
      - name: Gitpush
        run: |
          git config --global user.name 'repenaattori'
          git config --global user.email 'reimarii@oamk.fi'
          git add .
          git commit -m 'update'
          git push
          
