name: Harj1
on: workflow_dispatch
permissions: 
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.63.0-noble
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm ci
          npm test -- test1 > testi1.txt || true
      - run: npm test -- test2 > testi2.txt
      - name: Push
        if: failure() || success()
        run: |
          git config --global user.email 'reimarii@oamk.fi'
          git add testi1.txt testi2.txt
          git commit -m 'tests' || true
          git push
