name: Harj1
on: workflow_dispatch
permissions: 
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-node@v7
      - run: npx playwright install --only-shell chromium
      - run: |
          npm ci
          npm test -- test1 > testi1.md || true
      - run: npm test -- test2 > testi2.md
      - uses: actions/upload-artifact@v7
        if: failure()
        with:
          path: ./*.md
