name: kertaus
on: workflow_dispatch
permissions: 
  contents: write

env:
  MYNAME: Reima
  EVENT_NAME: ${{github.event_name}}
jobs:
  main:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Gitpush
        run: |
          git config --global user.name 'repenaattori'
          git config --global user.email 'reimarii@oamk.fi'
          git add .
          git commit -m 'update'
          git push
      - name: Lopputoimi
        if: failure()
        run: echo "Jottain...."
          
