name: Koe
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: |
          touch ./tests/uusi.txt
      - uses: actions/upload-artifact@v7
        with:
          path: |
            ./tests
            package.json
    
