name: Koe
on: workflow_dispatch
permissions: 
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/playwright:v1.63.0-noble
    steps:
      - uses: actions/checkout@v4
      - run: git --version
